### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by wepacad** [conwnet/shadowsocks-kodi#1]
Hello.
I installed your program. I am writing the IP address of the server, the port is an encryption method, but it does not work. KODI version 18.3. Linux kernel 4.14.78-4-osmc. Maybe there is some setup instructions
Thank you

**Comment by conwnet** [comment]
I have fixed many bugs in previous version, and tested passed on my kodi `LibreELEC 9.2.1 RPi2.arm`, you can try it again pls~ @wepacad

**Comment by wepacad** [comment]
Thanks for answer. I checked the new version of shadowsocks. My equipments: RPi3b+, OSMC Kodi 18.5, kernel: Linux 4.19.55-6-osmc. Also I have Chromium web browser (X11 desktop) and official Youtube add-on. After configure, I checked my IP. It's still not changed. Youtube and other blocked websites are not working. Maybe I'm doing something wrong. Could you explain how to configurate shadowsocks?

**Comment by conwnet** [comment]
Hi, please check three things:

1: Have you already restart the service after modified the shadowsocks config? Just click 'Disable' and 'Enable' in the addon overview panel.

2: ssh into kodi and run 'netstat -lntp', check if there are a listening local port default 1080 if you not modified it in config modal.

3: Have you already configure the system proxy in 'Kodi Settings -> System -> Internet access'? You should configure it with 'socks5 proxy' and port '1080'.

Please tell me if these three things above looks well, I'd like to fixed it.

**Comment by wepacad** [comment]
I'll write step by step what I did:
1. I configured shadowsocks client. Wrote Server IP, port, encryption type.
2. In "Optional" I kept default parameters (127.0.0.1:1080)
3. I disabled and enabled the shadowsocks.
4. On KODI i configured Internet access proxy: SOCKS5, 127.0.0.1:1080
5. In SSH I checked "netstat -lntp". Results:
`osmc@Altyn:~$ netstat -lntp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name

tcp        0      0 127.0.0.1:9090          0.0.0.0:*               LISTEN      -

tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -

tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      -

tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -

tcp        0      0 127.0.0.1:1080          0.0.0.0:*               LISTEN      -

tcp        0      0 0.0.0.0:36666           0.0.0.0:*               LISTEN      -

tcp6       0      0 ::1:9090                :::*                    LISTEN      -

tcp6       0      0 :::111                  :::*                    LISTEN      -

tcp6       0      0 :::80                   :::*                    LISTEN      -

tcp6       0      0 :::22                   :::*                    LISTEN      -

tcp6       0      0 :::36666                :::*                    LISTEN      -
`
6. With Chromium browser (X11 launcher) I opened whatismyipadress.com and I see IP of my country. :-(

**Comment by conwnet** [comment]
Through your infomation, I think the shadowsocks server service already worked. but the chrome seems not recognize the SOCKS5 proxy, you can install an extension for your chrome named [SwitchyOmega](https://github.com/FelisCatus/SwitchyOmega) and set it manually.

And I think the proxy is worked for kodi self, for example when you install an addon from kodi repository.
